name: Client Image CI

on:
  push:
    branches:
      - connect-backend-fronted-aks
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Read current version
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './VERSIONS/client_version'
          properties: 'version'

      - name: Current version
        run: echo ${{ steps.read_property.outputs.version }}        

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: ${{ steps.read_property.outputs.version }}
          version-fragment: 'bug'

      - name: Log in to ACR
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/my-frontend:${{ steps.bump_version.outputs.next-version }}
          build-args: |
            REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
            REACT_APP_GOOGLE_MAPS_API_KEY=${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}

      - name: Remove existing version file
        uses: JesseTG/rm@v1.0.3
        with:
          path: './VERSIONS/client_version'

      - name: Write new version
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './VERSIONS/client_version'
          property: 'version'
          value: ${{ steps.bump_version.outputs.next-version }}

      # - name: Git commit changes version number
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     file_pattern: ./VERSIONS/client_version
      #     branch: connect-backend-fronted-aks
      #     commit_message: 'Updated client_version to ${{ steps.bump_version.outputs.next-version }}'
      #     commit_user_name: GitHub Actions
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Git commit changes version number
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout connect-backend-fronted-aks
          git add ./VERSIONS/client_version
          git commit -m "Updated client_version to ${{ steps.bump_version.outputs.next-version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
